version: "3.7"

services:
  ranmal-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ranmal-api
    env_file: .env
    expose:
      - "$PORT"
    ports:
      - "$PORT:$PORT"
    command: npm run dev
